### ISSUE TITLE
Siliently enabling site-level settings is bad practice

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-mod_percipio#18]
This code silently enables the self enrolment plugin:
https://github.com/skillsoftadmin/moodle-mod_percipio/blob/master/externallib.php#L69

it also makes direct db calls to the config table rather than using correct set_config() api - bypassing logging and cache handling making it hard for an admin to understand why self-enrolment was enabled.

Ideally you should make this part of your installation/configuration docs (self enrolment must be enabled at the site level) and instead of enabling it, it should check if enabled and throw an error if not.

**Comment by skillsoftadmin** [comment]
Hi Dan, 
Yes you are right, these kind of configurations should be managed by an Admin, but As part of Percipio, we don't want our learner to miss any content due to the enrolment part, we want minimal steps to be performed by the learner in order to access the Percipio Content. 
Thanks for your valuable feedback :)

**Comment by danmarsden** [comment]
I didn't look at your code, but I'm not clear if you fixed anything there? - at the bare minimum you should be using set_config() instead of direct db calls - that way the change is logged correctly in the site config change log, and the cache for config data is also updated.
